# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fd19c2823b699d6dd6ed9f52a4a5cee46e44ac7d6181faffdfb83044e5963121ca4da564988a6fe3ed8258b8883fcc07156829338e4c2b3b1b419289779876f

test:
  secret_key_base: 00e20065982c11ffc730addcc60e43cb3b076d095894513a344112bd55628b8408be0e2b2851f37dfd1b3f164f7caa9310bf73d6bd92f376a389da743eafe293

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
